name: Angular Build and Deploy

on:
  push:
    # Despliega solo cuando se realiza un push a la rama master
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build --prod --base-href /shopping-cart/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: master
          folder: ./dist/shopping-cart
          token: ${{ secrets.TOKEN_DEPLOY }}
